#!/bin/bash
#set -ex
# Auto bumper script by Ettore Di Giacinto <mudler@sabayonlinux.org>
# License: MIT
# Requires yq and jq
# It bumps to latest tag annotated in the specs

# Options
AUTO_GIT="${AUTO_GIT:-false}"

START_GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
HUB_ARGS="${HUB_ARGS:--b $START_GIT_BRANCH}"
ROOT_DIR="${ROOT_DIR:-$PWD}"
TREE_DIR="${TREE_DIR:-$ROOT_DIR/packages}"

# Fetch depedendencies if not available
PATH=$PATH:$ROOT_DIR/.bin

JQ_RELEASE="${JQ_RELEASE:-1.6}"
YQ_RELEASE="${YQ_RELEASE:-3.3.4}"
HUB_RELEASE="${HUB_RELEASE:-2.14.2}"

hash jq 2>/dev/null || {
    mkdir $ROOT_DIR/.bin/;
    wget https://github.com/stedolan/jq/releases/download/jq-${JQ_RELEASE}/jq-linux64 -O $ROOT_DIR/.bin/jq
    chmod +x $ROOT_DIR/.bin/jq
}

hash yq 2>/dev/null || {
    mkdir $ROOT_DIR/.bin/;
    wget https://github.com/mikefarah/yq/releases/download/${YQ_RELEASE}/yq_linux_amd64 -O $ROOT_DIR/.bin/yq
    chmod +x $ROOT_DIR/.bin/yq
}

hash hub 2>/dev/null || {
    mkdir $ROOT_DIR/.bin/;
    wget https://github.com/github/hub/releases/download/v${HUB_RELEASE}/hub-linux-amd64-${HUB_RELEASE}.tgz -O $ROOT_DIR/.bin/hub
    chmod +x $ROOT_DIR/.bin/hub
}

# Luet tree package list
PKG_LIST=$(luet tree pkglist --tree $TREE_DIR -o json)

# For each package in the tree, get the path where the spec resides
# e.g. packages/acct-group/amavis/0/
for i in $(echo "$PKG_LIST" | jq -r '.packages[].path'); do

    PACKAGE_PATH=$i
    PACKAGE_NAME=$(echo "$PKG_LIST" | jq -r ".packages[] | select(.path==\"$i\").name")
    PACKAGE_CATEGORY=$(echo "$PKG_LIST" | jq -r ".packages[] | select(.path==\"$i\").category")
    PACKAGE_VERSION=$(echo "$PKG_LIST" | jq -r ".packages[] | select(.path==\"$i\").version")

    STRIPPED_PACKAGE_VERSION=${PACKAGE_VERSION%\+*}
    VERSION=$STRIPPED_PACKAGE_VERSION

    # Check if ignore flag is present
    AUTOBUMP_IGNORE=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.ignore"')
    if [ "${AUTOBUMP_IGNORE}" = "1" ] ; then
      continue
    fi

    # Best effort: get original package name from labels
    GITHUB_REPO=$(yq r $PACKAGE_PATH/definition.yaml 'labels."github.repo"')
    GITHUB_OWNER=$(yq r $PACKAGE_PATH/definition.yaml 'labels."github.owner"')

    # Strategy can be: release, tags or "refs"
    # Refs parses thru git tags
    AUTOBUMP_STRATEGY=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.strategy"')

    # Package can opt-in for automatic revdeps revbump
    AUTOBUMP_REVDEPS=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.revdeps"')

    # Prefix to trim from the version
    TRIM_PREFIX=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.trim_prefix"')

    # A json map of replace rules
    STRING_REPLACE=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.string_replace"')


    # A json list of strings contained in the releases to skip (e.g. betas)
    SKIP_IF_CONTAIN=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.skip_if_contains"')

    # You can specify a string match that should be contained in the versions
    # to be considered. Valid for "refs" and tagging strategy
    VERSION_CONTAINS=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.version_contains"')

    AUTOBUMP_REFIX=$(yq r $PACKAGE_PATH/definition.yaml 'labels."autobump.prefix"')
    SNAPSHOT_PREFIX=${AUTOBUMP_REFIX:-0.}
    if [[ "$AUTOBUMP_STRATEGY" == "release" ]]; then
        LATEST_TAG=$(curl https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/releases/latest -s | jq .tag_name -r)
    elif [[ "$AUTOBUMP_STRATEGY" == "refs" ]]; then
        LATEST_TAG=$(curl https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/git/refs/tags -s | jq '.[].ref | sub("refs\/tags\/"; "") | select(. | test("'$VERSION_CONTAINS'"))' -r | tail -n1 )
    elif [[ "$AUTOBUMP_STRATEGY" == "snapshot" ]]; then
        LATEST_TAG=${SNAPSHOT_PREFIX}$(date +%Y%m%d)
    else
        LATEST_TAG=$(curl https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/tags -s | jq -r '.[].name | select(. | test("'$VERSION_CONTAINS'"))' -r | head -1 )
    fi

    LATEST_TAG=${LATEST_TAG#v} # semver
    LATEST_TAG=${LATEST_TAG#$TRIM_PREFIX} # go..

    for i in $(echo "$STRING_REPLACE" | jq -r 'keys[]'); do
        WITH=$(echo "$STRING_REPLACE" | jq -r '."'$i'"')
        echo "Replacing $i with '$WITH'"
        LATEST_TAG=$(echo "$LATEST_TAG" | sed -r 's/'$i'+/'$WITH'/g')
    done

    for i in $(echo "$SKIP_IF_CONTAIN" | jq -r '.[]'); do
        if [[ "$LATEST_TAG"  =~ "$i" ]]; then
            echo "Skipping because latest release contains '$i'"
            continue 2
        fi
    done

    echo "Latest tag for $PACKAGE_NAME is $LATEST_TAG"

    [[ "$LATEST_TAG" == "null" ]] && LATEST_TAG=
    # versions are mismatching. Bump the version
    if [ -n "$LATEST_TAG" ] && [ $LATEST_TAG != "$STRIPPED_PACKAGE_VERSION" ] ; then
        echo "Bumping spec version of $PACKAGE_CATEGORY/$PACKAGE_NAME to $LATEST_TAG"

        BRANCH_NAME="bump_${PACKAGE_NAME}_${PACKAGE_CATEGORY}"
        if [ "${AUTO_GIT}" == "true" ]; then
            git branch -D $BRANCH_NAME
            git checkout -b $BRANCH_NAME
        fi

        # Generate new folder after the new version
        # e.g. tree/package/1.1 to tree/package/1.2
        package_dir=$(dirname $PACKAGE_PATH)

        # Update runtime version
        yq w -i $PACKAGE_PATH/definition.yaml version "$LATEST_TAG" --style double

        if [ "${AUTO_GIT}" == "true" ]; then
            git add $PACKAGE_PATH/
            git commit -m "Bump $PACKAGE_CATEGORY/$PACKAGE_NAME to $LATEST_TAG"
            git push -f -v origin $BRANCH_NAME

            # Branch is ready now to open PR
            hub pull-request $HUB_ARGS -m "$(git log -1 --pretty=%B)"

            git checkout $START_GIT_BRANCH # Return to original branch
        fi

        if [[ "$AUTOBUMP_REVDEPS" == "true" ]]; then
            for i in $(luet tree pkglist -t $PWD -m $PACKAGE_CATEGORY/$PACKAGE_NAME --revdeps); do

                if [ "${AUTO_GIT}" == "true" ]; then
                    git checkout $BRANCH_NAME # Return to bump branch
                fi

                echo "Revbump for $i"
                IFS=/ read -a package <<< $i
                path=$(echo "$PKG_LIST" | jq -r ".packages[] | select(.name==\"${package[1]}\" and .category==\"${package[0]}\").path")

                # Update runtime version
                luet tree bump -f $path/definition.yaml

                if [ "${AUTO_GIT}" == "true" ]; then
                    git add $path/
                    git commit -m "Revbump $PACKAGE_CATEGORY/$PACKAGE_NAME caused by $PACKAGE_CATEGORY/$PACKAGE_NAME"
                    git push -f -v origin $BRANCH_NAME

                    # Branch is ready now to open PR
                    hub pull-request $HUB_ARGS -m "$(git log -1 --pretty=%B)"

                    git checkout $START_GIT_BRANCH # Return to original branch
                fi
            done
        fi
    fi
done
